function opt = initializeParameters()
    opt.n_chans = 21; 
    opt.n_classes = 2;
    opt.n_start_chans = 25;
    opt.n_filters_time=opt.n_start_chans;
    opt.n_filters_spat=opt.n_start_chans;
    opt.n_chan_factor = 2;
    opt.input_time_length= 6000;
    opt.n_filters_2 = (opt.n_start_chans * opt.n_chan_factor);
    opt.n_filters_3 = (opt.n_start_chans * (opt.n_chan_factor ^ 2.0));
    opt.n_filters_4 = (opt.n_start_chans * (opt.n_chan_factor ^ 3.0));
    opt.filter_length_2=10;
    opt.filter_length_3=10;
    opt.filter_length_4=10;
    opt.final_conv_length=67;
    opt.filter_time_length=10;
    opt.pool_time_stride = 3;
    opt.conv_stride = opt.pool_time_stride;
    opt.pool_stride = 1;
    opt.pool_time_length = 3;
    opt.drop_prob = 0.5;
    opt.targetLength = 6000;
    opt.max_recording_mins = 18;%how many minutes of data to clip to
    opt.sec_to_cut = 60;
    opt.desiredFs = 100; %frequency to resample data at
    opt.originalFs = [];
    opt.total_recording_mins = 16; %how many minutes of data to use
    opt.iter_recording_mins = 1.1;
    opt.max_abs_val = 800; %amplitude value (+/-) to clip data to
    opt.sec_to_cut = 60; %how many of seconds from initial recording to remove
    opt.max_epoch = 35;
    opt.init_lr = 1e-3;
    opt.mini_batch_size = 64;
    opt.cropSize = 67;
    opt.val_patience = 6;
end